name = "92lottery-api"
main = "src/worker/index.ts"
compatibility_date = "2024-04-25"

# Production configuration
[env.production]
workers_dev = true
route = "api.92lottery.dev/*"

[[env.production.d1_databases]]
binding = "DB"
database_name = "lottery92_db"
database_id = "3c26864a-5cbb-43c9-8b16-5730721c3dd3"

# Static assets configuration
[site]
bucket = "./out"
