[build]
command = "bash ./build.sh"
output_directory = "out"
node_version = "18.18.0"

[build.environment]
NODE_VERSION = "18.18.0"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_FORCE = "true"
NPM_CONFIG_PACKAGE_LOCK = "false"
CI = "false"
NEXT_DISABLE_ESLINT = "1"
NEXT_TELEMETRY_DISABLED = "1"
